#!/bin/sh
echo Provisioning...
sudo sh -c 'date > /etc/vagrant_provisioned_at'
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -q libssl-dev libffi-dev python-pip libpython-dev
sudo pip install -r /vagrant/requirements.txt
